services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4000:4000"
    env_file: .env
    command: npm run start
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    command: npm run start:worker
