FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/web/package.json apps/web/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN npm install
COPY . .
RUN npm run build:shared && npm run build:web
EXPOSE 3000
CMD ["npm", "run", "dev:web"]
