import { Router } from "express"; import { z } from "zod"; import { tracksService } from "../services/tracks.service.js";
const s=z.object({release_id:z.string().uuid(),artist_id:z.string().uuid(),title:z.string().min(1),version:z.string().optional(),isrc:z.string().optional(),track_number:z.number().int().optional(),explicit:z.boolean().optional()});
export const tracksRoutes=Router();
tracksRoutes.get("/tracks",async(r,sn)=>sn.json((await tracksService.list(r.auth!.organizationId)).data));
tracksRoutes.post("/tracks",async(r,sn)=>sn.status(201).json((await tracksService.create(r.auth!.organizationId,s.parse(r.body))).data));
tracksRoutes.get("/tracks/:id",async(r,sn)=>sn.json((await tracksService.byId(r.auth!.organizationId,r.params.id)).data));
tracksRoutes.patch("/tracks/:id",async(r,sn)=>sn.json((await tracksService.update(r.auth!.organizationId,r.params.id,s.partial().parse(r.body))).data));
tracksRoutes.delete("/tracks/:id",async(r,sn)=>{await tracksService.delete(r.auth!.organizationId,r.params.id);sn.status(204).send();});
tracksRoutes.post("/tracks/:id/approve",async(r,sn)=>sn.json((await tracksService.approve(r.auth!.organizationId,r.params.id)).data));
tracksRoutes.post("/tracks/:id/reject",async(r,sn)=>sn.json((await tracksService.reject(r.auth!.organizationId,r.params.id)).data));
